#cloud-config

apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - docker-ce
  - docker-ce-cli
  - containerd.io

# Enable ipv4 forwarding, required on CIS hardened machines
write_files:
  - path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
    content: |
      net.ipv4.conf.all.forwarding=1

# create the docker group
groups:
  - docker

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [docker]

runcmd:
  - /usr/bin/sleep 10
  - /usr/bin/docker pull 550157292651.dkr.ecr.eu-central-1.amazonaws.com/minecraft-server:latest
  - /usr/bin/docker run -d -p 25565:25565 --restart=always -e S3_BUCKET="${minecraft_bucket}" 550157292651.dkr.ecr.eu-central-1.amazonaws.com/minecraft-server:latest
