#cloud-config

apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

package_update: true

package_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - amazon-ecr-credential-helper
  - awscli

# Enable ipv4 forwarding, required on CIS hardened machines
write_files:
  - path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
    content: |
      net.ipv4.conf.all.forwarding=1
  - path: /home/ubuntu/.docker/config.json
    content: |
      {
      	"credsStore": "ecr-login"
      }
  - path: /root/.docker/config.json
    content: |
      {
      	"credsStore": "ecr-login"
      }
  - path: /etc/ssh/sshd_config
    append: true
    content: |
      ClientAliveInterval 600
      ClientAliveCountMax 0
  - path: /etc/cron.d/minecraft
    content: |
      */5 * * * * ubuntu aws s3 sync --exclude "*" --include "world/*" --include "logs/*" /opt/minecraft s3://${minecraft_bucket}

# create the docker group
groups:
  - docker

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [docker]

runcmd:
  - mkdir /opt/minecraft
  - aws s3 sync --exclude "*" --include "world/*" --include "logs/*" s3://${minecraft_bucket} /opt/minecraft
  - chmod +xwr --recursive world/
  - chmod +xwr --recursive logs/
  - docker run
    -d
    -e EULA=TRUE
    -e JVM_XX_OPTS="-XX:InitialRAMPercentage=75 -XX:MaxRAMPercentage=75"
    -p 25565:25565
    --restart=always
    -v /opt/minecraft/world:/data/world
    -v /opt/minecraft/logs:/data/logs
    itzg/minecraft-server
